[package]
name = "rs-concepts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# 01 - Hello World
[[bin]]
name = "hello-world"
path = "src/hello-world.rs"

[[bin]]
name = "variables"
path = "src/variables.rs"
